Kubernetes intro
otus-kuber-2020-11/drozdnikita_platform pull request #2
Opened 2021-01-09 08:56 UTC by drozdnikita

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist:
 - [ ] Выставлен label с темой домашнего задания

2021-01-11 17:29 UTC, Jasstkn requested changes
Добрый день. Оставила комментарий, что нужно поправить. В остальном все сделано верно, как только внесете изменение - приму домашку

2021-01-11 17:29 UTC, Jasstkn commented on kubernetes-intro/web-pod.yaml
> +    image: drozdnikita/drozd_web_app:1.0.0
контейнеру нужно имя, иначе под не задеплоится

2021-01-13 18:02 UTC, drozdnikita commented on kubernetes-intro/web-pod.yaml
> +    image: drozdnikita/drozd_web_app:1.0.0
Добрый день,

исправил. проверьте, пожалуйста

2021-01-22 19:22 UTC, Jasstkn approved these changes
Approved! 🖖

2021-01-22 19:22 UTC, merged