Kubernetes controllers
otus-kuber-2020-11/drozdnikita_platform pull request #3
Opened 2021-01-09 14:07 UTC by drozdnikita

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist:
 - [ ] Выставлен label с темой домашнего задания

2021-01-11 17:58 UTC, Jasstkn requested changes
Добрый день.
Во время прохождения тестов возникла ошибка:
> TestKubernetesPaymentDeployment 2021-01-11T17:55:00Z command.go:158: error: the path "/home/mariak/hw/drozdnikita_platform/kubernetes-controllers/paymentservice-deployment.yaml" does not exist

2021-01-13 18:11 UTC, drozdnikita commented
> Добрый день.
> Во время прохождения тестов возникла ошибка:
> 
> > TestKubernetesPaymentDeployment 2021-01-11T17:55:00Z command.go:158: error: the path "/home/mariak/hw/drozdnikita_platform/kubernetes-controllers/paymentservice-deployment.yaml" does not exist

Добрый день, исправил имена файлов

2021-01-22 19:11 UTC, Jasstkn approved these changes
Теперь все верно!

2021-01-22 19:11 UTC, Jasstkn commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +      - key: node-role.kubernetes.io/master
Этот вариант тоже верный, поды запустятся на всех нодах:
```
 tolerations:
   - operator: Exists
```

2021-01-22 19:11 UTC, merged

2021-01-23 09:12 UTC, drozdnikita commented on kubernetes-controllers/node-exporter-daemonset.yaml
> +      - key: node-role.kubernetes.io/master
принято, спасибо!